name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '26 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Pip install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch latest data
      run: |-
        scrapy crawl jetcoatms -O jetcoatmsraw.jl
        cat jetcoatmsraw.jl | jq -s 'sort_by(.id) |.[]' > jetcoatms.jl
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add jetcoatms.jl
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
